version: '3.1'

services:
  web:
    image: nginx:mainline
    build: .
    volumes:
      - type: bind
        source: ./site
        target: /usr/share/nginx/html
      - type: bind
        source: ./nginx/conf/includes/headers.conf
        target: /etc/nginx/conf.d/headers.conf
    ports:
      - "8080:80"

  owasp:
    image: owasp/zap2docker-stable
    command: zap-baseline.py -c zap.conf -t http://web:80/ -I -r zap_report.html
    volumes:
      - .:/zap/wrk/
    links: ["web"]
    profiles: ["owasp-scan"]
