# This workflow runs on all merges to main

name: Deploy main after each merge

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4

      - name: Install node dependencies
        run: npm ci

      - name: Build with Eleventy
        run: npm run build

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: sandbox-gsa
          cf_space: neil.martinsen-burrell
          cf_manifest: "ops/manifests/manifest.yaml"
